### ISSUE TITLE
privacy_flag not working?

### ISSUE THREAD

**Issue by herebebogans** [flood-io/ruby-jmeter#100]
Hi ,

1st off this is an awesome project - as newbies to Jmeter this has enabled us to get up and running quickly from the comfort of ruby.

I've tried a few end.flood tests like so

> end.flood(
>       'MY_API_KEY'
>       name: 'my_test',
>       privacy_flag: 'public',
>       project: 'MY_PROJECT',
>     )

The test gets executed fine but in the flood io dashboard I still need to click "Share" to make it public.

**Comment by herebebogans** [comment]
Having a look through the code and some recent commits the syntax needs to be

> privacy: 'public'

**Comment by 90kts** [comment]
That's correct, the actual form field is `flood[privacy_flag] = public|private` on the Flood API https://help.flood.io/docs/api-create-floods

but for convenience in ruby-jmeter we just use the privacy parameter here: https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/extend/misc/flood.rb#L32

**Comment by herebebogans** [comment]
The Readme.md example shows privacy_flag ..

**Comment by 90kts** [comment]
Fixed thanks
