### ISSUE TITLE
Can't log in with a Rails App!

### ISSUE THREAD

**Issue by Mardiniii** [flood-io/ruby-jmeter#113]
Hi guys, 

I'm trying to make a simple login for a Rails WEB application using ```ruby-jmeter```, I followed this [tutorial](https://blog.flood.io/how-to-test-a-ruby-on-rails-application-with-jmeter/) from [flood.io](flood.io) but I can't achieve my goal, I think I have a problem with the authenticity_token, I'm implementing the next code: 

```ruby
require 'ruby-jmeter'

test do  
  defaults domain: 'quincena.me'

  cache clear_each_iteration: true
  cookies

  threads count: 50, loops: 1 do

    random_timer 1000, 3000
    extract name: 'authenticity_token', regex: 'meta content="(.+?)" name="csrf-token"'

    transaction '01_visit_sign_in_page' do
      visit '/users/sign_in' do
        assert contains: 'Iniciar Sesión', scope: 'main'
      end
    end

    transaction '02_sign_in' do
      submit '/users/sign_in', {
        fill_in: {
          'utf8'               => '✓',
          'authenticity_token' => '${authenticity_token}',
          'user[email]'        => 'valid_email',
          'user[password]'     => 'valid_password',
          'commit'             => 'Iniciar Sesión'
        }
      } do
        assert contains: 'Panel de Control'
      end
    end

    transaction '03_pay_payroll_view' do
      visit '/pay_payroll' do
        assert contains: 'Pagar Nómina', scope: 'main'
      end
    end
  end

  # Debug JMeter test plan
  view_results_tree
  summary_report

  # Display testing results
  graph_results
  aggregate_graph

end.run(gui: true)
```

I will really appreciate if somebody can help me to solve this issue, our team is trying to build some performances, load and stress tests and this script is the key to start with the process.

**Comment by sjethvani** [comment]
When dealing with script issues in ruby-jmeter , I always create .jmx file first from .rb file (ruby-jmeter script file) & will open that file in Jmeter-Gui and run my testcase first there to debug problem by adding listeners and looking at console  . I will suggest you to do same thing .

**Comment by Mardiniii** [comment]
Thanks @sjethvani!

**Comment by blahutka** [comment]
Hi @Mardiniii , did you fix this, I still get `ActionController::InvalidAuthenticityToken` from the rails. But the tokens I'm passing in the form is the same as in meta tag.

**Comment by fidalgo** [comment]
@blahutka same here. Any idea?
