### ISSUE TITLE
Open3 unsupported spawn option when using JRuby

### ISSUE THREAD

**Issue by timkoopmans** [flood-io/ruby-jmeter#12]
jruby/lib/jruby.jar!/jruby/kernel19/process.rb:4 warning: unsupported spawn option: in
TypeError: wrong exec option: [:out, :err]
 _spawn_internal at org/jruby/RubyProcess.java:1091
any ideas
e.g. test do
 threads count: 10 do
   visit name: 'Pet Shop Home', url: 'http://54.252.57.49/MSPetShop'
 end
end.run(
 path: 'C:\apache-jmeter-2.9\bin', 
 file: 'jmeter.jmx', 
 log: 'jmeter.log', 
 jtl: 'results.jtl')

**Comment by reach2jeyan** [comment]
@maxl0rd @swistaczek @90kts 

Any update on this? I get a similar error

```
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - /Users/admin/Desktop/jmeter (Errno::ENOENT)
	from /Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open3.rb:190:in `popen2e'
	from /Users/admin/.rvm/gems/ruby-2.4.1/gems/ruby-jmeter-3.1.08/lib/ruby-jmeter/dsl.rb:43:in `run'
```

My code is:
```
test do
  threads count: 10 do
    visit name: 'Google search', url: 'http://google.com'
  end
end.run(
    path: '/Users/admin/Desktop/',
    file: 'sampleplan.jmx',)
```
