### ISSUE TITLE
Websocket samplers plugin supported ?

### ISSUE THREAD

**Issue by Barbeblanche** [flood-io/ruby-jmeter#135]
Hi !

Is Websocket samplers plugin supported by flood-io ?
Or Is it possible to include differents plugin ?

Thanks.

**Comment by jrizio** [comment]
Hi there!

Yes it is possible to run 3rd party samplers (including 3rd party websocket samplers) using the Flood platform.

You just have to zip the jar files up into a zip file and upload them when running a new Flood through the UX.

If you haven't already - feel free to signup for a free trial account and contact support if you require any assistance or have any issues setting up your test.
