### ISSUE TITLE
How to post x-www-form-urlencoded body?

### ISSUE THREAD

**Issue by treymerkley** [flood-io/ruby-jmeter#150]
So far I'm not finding anything in the code or examples on how to post something other than a raw_body. How can I post requests using bodies other than raw?

**Comment by ChrisMaze** [comment]
> So far I'm not finding anything in the code or examples on how to post something other than a raw_body. How can I post requests using bodies other than raw?

Hi @treymerkley 
I also met this issue and found a way to figure out it:
just use the raw body and wet the key: value as a string
 - set your header 
```ruby
{name: 'Content-Type', value: 'application/x-www-form-urlencoded'}
```
- set body
```ruby
raw_body: 'key=value'
```
it works well

**Comment by treymerkley** [comment]
I didn't end up using ruby-jmeter much longer, so I'll accept this as solving the issue.
