### ISSUE TITLE
need to sort entries by startedDateTime

### ISSUE THREAD

**Issue by SamHasler** [flood-io/ruby-jmeter#36]
The HAR spec does not require entries to be saved in order so you need to sort them before outputting them in `.jmx` files. 

NB: Chrome does not save entries in order and [the bug to save them in order was closed as WontFix](https://code.google.com/p/chromium/issues/detail?id=460027)

**Comment by 90kts** [comment]
Hi Sam, I assume you're referring to the Har2Jmx feature on Flood IO (not necessarily this repo)?
