### ISSUE TITLE
How can I set simple_data_writer properties?

### ISSUE THREAD

**Issue by mtakahashi-ivi** [flood-io/ruby-jmeter#37]
Hello,

I wrote configuration for simple_data_writer like following.
```ruby
simple_data_writer name: "Result", fieldNames: true, xml: false, saveAssertionResultsFailureMessage: true, responseDataOnError: true, filename:"file_name"
```

But configuration under "SampleSaveConfiguration" element was not changed.
How can I change those values?

Regards,
Masanori Takahashi

**Comment by 90kts** [comment]
Hi Masanori, please use the `update_at_xpath` parameter like this:

https://github.com/flood-io/ruby-jmeter/blob/master/examples/basic_assertion_results.rb

**Comment by mtakahashi-ivi** [comment]
Thank you!
