### ISSUE TITLE
error on opening created jtl file

### ISSUE THREAD

**Issue by roshanjohn** [flood-io/ruby-jmeter#39]
On running tests, the jtl file is created. Here is the content of the jtl file

1431002449675|807|Home Page|200|Home Page Users 1-1|true|20531|1|1|311|1|0|null

On opening the jtl file from JMeter UI, the following error is thrown:
2015/05/07 16:54:09 WARN  - jmeter.save.CSVSaveService: Error parsing field 'timeStamp' at line 1 java.text.ParseException: No date-time format found matching 1431002449675|807|Home Page|200|Home Page Users 1-1|true|20531|1|1|311|1|0|null

How to circumvent this error?

**Comment by 90kts** [comment]
Make sure that the jmeter.properties file is set accordingly: 

`jmeter.save.saveservice.timestamp_format=ms`

**Comment by roshanjohn** [comment]
the configuration is set as mentioned. But still facing the issue.

**Comment by pmouawad** [comment]
check your separator:

- jmeter.save.saveservice.default_delimiter=|

**Comment by roshanjohn** [comment]
yes Philippe. The delimiter configured was '|'
This threw an error because the output_format was 'csv'.

Modified the delimiter to ',' and now, the jtl file can be loaded.

**Comment by abhishekgarg0196** [comment]
at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_211]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.text.ParseException: No date-time format found matching 
	at org.apache.jmeter.save.CSVSaveService.makeResultFromDelimitedString(CSVSaveService.java:233) ~[ApacheJMeter_core.jar:5.1.1 r1855137]
	... 41 more
