### ISSUE TITLE
Aggregate Report vs. Standard Plugins

### ISSUE THREAD

**Issue by josdotso** [flood-io/ruby-jmeter#48]
I did some digging and found that Aggregate Report format available in the GUI is only obtainable from the command line through post processing.  The Standard Plugins library contains a method of doing this.  Would you be willing to support a true Aggregate Report?

./JMeterPluginsCMD.sh --generate-csv new.csv --input-jtl existing.jtl --plugin-type AggregateReport

http://stackoverflow.com/a/7992846

http://www.quora.com/How-do-we-analyze-reports-in-JMeter/answers/9712920

https://code.google.com/p/gisgraphy/source/browse/trunk/gisgraphy/src/bench/bin/aggregate_sample.sh?r=111&spec=svn362

**Comment by 90kts** [comment]
At this stage we're not planning on adding different report generation options to the code base, but you're welcome to submit a PR if you'd like to see something included.

Regards,
​Tim
