### ISSUE TITLE
Non-standard interface for jmeter-plugins

### ISSUE THREAD

**Issue by cyberw** [flood-io/ruby-jmeter#55]
def initialize(name, params={}) 
instead of 
def initialize(params={}). 

This is really confusing at times, because it is totally valid ruby to use the normal syntax in a test plan, but that results in having a hash in the variable name, and nil in parameters :-/

Can we change this? Or was there a good reason to have it this way?

**Comment by 90kts** [comment]
It should just be params - this has probably slipped in via contributions in the past I haven't kept my eye on more closely. Happy for you to PR the change.

Regards,
​Tim

**Comment by cyberw** [comment]
If I make any changes in this area I will make sure to update them all.
