### ISSUE TITLE
Documentation for developers: Environment setup

### ISSUE THREAD

**Issue by pmouawad** [flood-io/ruby-jmeter#59]
Hello,
Is there somewhere a documentation describing:
- How to setup dev environment
- Install local gem through gem or rake ?
- Test local changes ?

Thanks

**Comment by pmouawad** [comment]
See: 
https://github.com/flood-io/ruby-jmeter/pull/61

**Comment by 90kts** [comment]
Hopefully this helps a bit: https://github.com/flood-io/ruby-jmeter#contributing and after ..
