### ISSUE TITLE
jsr223_assertion mix up script with scriptLanguage

### ISSUE THREAD

**Issue by anderseriksson** [flood-io/ruby-jmeter#62]
The generated JMX has the script and scriptLanguage parameters mixed up when using the jsr223_assertion component <JSR223Assertion>:
```xml
            <stringProp name="script">javascript</stringProp>
            <stringProp name="scriptLanguage">//My Javascript code ends up here</stringProp>
```
Of course this gives error in JMeter ( JSR223 script Assert state javax.script.ScriptException: Cannot find engine named: '//My Javascript... ). This happens with JRuby 9.0.1.0.

Looking at the source it seems that the order of these fields in the XML template  is significant (!) in the file ruby-jmeter/dsl/jsr223_assertion.rb. 

So changing to the following helps:

```xml
<JSR223Assertion guiclass="TestBeanGUI" testclass="JSR223Assertion" testname="#{testname}" enabled="true">
  <stringProp name="parameters"/>
  <stringProp name="filename"/>
  <stringProp name="cacheKey"/>
  <stringProp name="script"/>
  <stringProp name="scriptLanguage"/>
</JSR223Assertion>)
```
which is also similar to the other JSR223 components in the same directory.

I should be able to make a PR if you need.

**Comment by pmouawad** [comment]
See:
https://github.com/flood-io/ruby-jmeter/pull/63

**Comment by 90kts** [comment]
Hi there,

Sorry for the delay, the better way to approach this (as we cannot predict the ordering from the IDL / source) is to use specific xpath statements to update elements of choice e.g. https://github.com/flood-io/ruby-jmeter/blob/master/examples/jsr223_assertion.rb
