### ISSUE TITLE
Defaults download_resources does not turn flag off

### ISSUE THREAD

**Issue by coryasato** [flood-io/ruby-jmeter#70]
I've omitted download_resources or set it to false, both do not unflag Retrieve All Embedded Resources in HttpRequestDefaults.  Something I'm missing?

    test do
        defaults download_resources: false
    end.run(gui: true)

**Comment by anderseriksson** [comment]
We set this flag

image_parser: false

to avoid implicit download of embedded resources.

**Comment by 90kts** [comment]
:+1:
