### ISSUE TITLE
Use Array of URLs to visit

### ISSUE THREAD

**Issue by stoplion** [flood-io/ruby-jmeter#74]
Is there a way to use an array of paths to have Ruby-Jmeter to `visit`? I have an array of thousands of URLs. Same host, just different paths.

```
[
  'foo.com',
  'foo.com/bar',
  'foo.com/bar/main-results',
  ....
]
```

**Comment by 90kts** [comment]
You'd be best of using JMeter's CSV data set for this: https://github.com/flood-io/ruby-jmeter/blob/master/examples/basic_flood_with_csv.rb

**Comment by stoplion** [comment]
thanks!
