### ISSUE TITLE
Output variables from extracted html response to JTL?

### ISSUE THREAD

**Issue by stoplion** [flood-io/ruby-jmeter#76]
Is it possible to extract data from an HTML response of GET request and output this value to `JTL` file?

`extract css: "div#global-footer-system-info", name: 'Test123', variable: 'Test123'`

Also from the response header of GET request?
`extract regex: "CustomHeaderName: '(.+?)'", name: 'Test123', variable: 'Test123'`

**Comment by tilln** [comment]
You're looking for a JMeter feature called [sample_variables](http://jmeter.apache.org/usermanual/listeners.html#sample_variables) which can be configured in a properties file, e.g. `sample_variables=Test123`
HTH

**Comment by 90kts** [comment]
Correct, this would be your best approach.
