### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Prateeknarayan15** [flood-io/ruby-jmeter#77]
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-jmeter:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for main() in -lstdc++... no
creating Makefile

make
compiling unf.cc
make: g++: Command not found
make: *** [unf.o] Error 127

Gem files will remain installed in /var/lib/gems/1.9.1/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/unf_ext-0.0.7.2/ext/unf_ext/gem_make.out

**Comment by 90kts** [comment]
duplicate #79
