### ISSUE TITLE
trouble

### ISSUE THREAD

**Issue by Prateeknarayan15** [flood-io/ruby-jmeter#78]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- ruby-jmeter (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from mytest.rb:2:in `<main>'

**Comment by cpalafox** [comment]
just add jmeter/bin to your PATH
