### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by Prateeknarayan15** [flood-io/ruby-jmeter#79]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- ruby-jmeter (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from mytest.rb:2:in `<main>'

**Comment by 90kts** [comment]
Can you please try with a more recent version of Ruby e.g. 2.3.x

**Comment by Aleksandaar** [comment]
Run test with`bundle exec`, like: `bundle exec ruby your_test.rb`, so the gem library would be loaded before running the test.
