### ISSUE TITLE
Unable to set global properties on to jmeter 

### ISSUE THREAD

**Issue by ashutoshg** [flood-io/ruby-jmeter#80]
We are using a number of JMeter servers in Kuberneties as a grid to generate the load in NFTs. 
As part of running the tests, we need to set some properties, which should be set/sent across all the grid servers. These properties can only be decided after starting up the grid and before kicking of the tests (i.e. before calling run method). The way to achieve this as per JMeter documentation is to set  global properties with -G option while executing the command line on controller (example below). (for details. http://jmeter.apache.org/usermanual/get-started.html#options)

Example.
````
jmeter -n -t pipeline_test.jmx -j pipeline_test.log -Gsome_property_1=1 -Gsome_property_2=2000000001 -Gsome_property_3=2000000000 -l pipeline_test.jtl -q user.properties -R 192.168.99.100,192.168.99.101

````
As per current implementation of the DSL, we are not able to set these properties. 
Looking at above link which is detailing various options available on JMeter command line, what we would like to propose is to have open option like for e.g. 'otherJmeterOptions' which can be used to set any extra params that should be passed on to JMeter executable directly. This will also cater for future releases where JMeter provides any new command line options.
````
end.run(
        file: scenario.project_filename,
        log: scenario.log_filename,
        jtl: scenario.results_filename,
        remote_hosts: File.readlines(ips.txt', __FILE__)[0],
        properties: scenario.resource_filename('user.properties'),
        debug: true,
        otherJmeterOptions: "-Gsome_property_1=1 -Gsome_property_2=2000000001 -Gsome_property_3=2000000000"
    )
````

**Comment by 90kts** [comment]
We won't be supporting custom JMeter options from the command line. Your best option is to generate a test plan using ruby-jmeter with the .jmx method. This will write a file to your filesystem which you can then run as you please.
