### ISSUE TITLE
Generated DSL source out of date / does not match idl.xml

### ISSUE THREAD

**Issue by timothyp** [flood-io/ruby-jmeter#87]
In the course of investigating an issue in the DSL source under `lib/ruby-jmeter/dsl`, I found that it looks like it's out of date.  I understand the source is auto-generated.  However, simply running `ruby lib/ruby-jmeter/idl.rb` in a fresh copy of the repository results in a number of source files in `lib/ruby-jmeter/dsl` changing.  Looking at the git history shows that `lib/ruby-jmeter/idl.xml is newer than most of the files in `lib/ruby-jmeter/dsl`.  It is older than 1 or 2 though.

This implies that the generated source is not all up to date, but has also in a couple of cases been tweaked by hand and/or auto-generated changes have been selectively committed since most recent `idl.xml` commit.

There are cases where the XML has changed, but this isn't reflected in the auto-generated file in the repo (e.g. `embedded_url_re` disapeared from the idl.xml https://github.com/flood-io/ruby-jmeter/commit/c14caf3cb4281510d73dc9c5f727e8c9c796eeae#diff-2391882be85be2c7f559dfaa99483e3fL94 but not from the autogenerated https://github.com/flood-io/ruby-jmeter/blob/3a09b4e5ad6112d88bcb0c632308e9365ff7d40d/lib/ruby-jmeter/dsl/http_request_defaults.rb#L31 ).  There are also cases where things have been manually tweaked (e.g. the conditional creation of start/end indexes at https://github.com/flood-io/ruby-jmeter/blob/3a09b4e5ad6112d88bcb0c632308e9365ff7d40d/lib/ruby-jmeter/dsl/foreach_controller.rb#L20-L21

This makes it a bit tricky to decide which route to take when fixing a bug in the DSL code.  Should it be fixed by changing the DSL generation code, or should it be fixed by tweaking the generated code by hand, after which the file joins the list of existing (originally-autogenerated) files which aren't simply the result of running the DSL generation?  My concern with the latter route is that it adds to the special cases.  I would think this should be avoided, because the more special cases there are, the less relevant/use the autogeneration becomes and the more overhead with jmeter updates in the long run.  Any thoughts?

**Comment by 90kts** [comment]
Hi Tim thanks for taking the time to look into this.

It's true, there are some limitations to auto generating the classes from the source XML, some of which require domain experience. The downsides is that this isn't done frequently enough.

At this stage I'm not sure of the best way to proceed. I feel like we need to be able to create exceptions as there will always be special edge cases to work around.

**Comment by 90kts** [comment]
Hello again, I have since refactored the code base so that the IDL can always be run as-is with the output in lib/dsl/* untouched as intended.

To supplement some auto generated DSL by this process, there is now a lib/extend/** directory structure where you can provide specific overrides e.g. https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/extend/controllers/foreach_controller.rb

FWIW I don't think we can avoid special cases which is why I opted for this approach. Let me know your thoughts.
