### ISSUE TITLE
User Parameters per-iteration setting is ignored

### ISSUE THREAD

**Issue by timothyp** [flood-io/ruby-jmeter#88]
It seems this is because of invalid XML in `dsl/user_parameters.rb`.

I've developed a fix plus unit test for this.

Actually, I've developed 3 fixes, but I'm not sure which to use, otherwise I'd have also submitted a PR!

1. The first thing I did was to tweak the XML by hand.  However, when I started thinking about contributing the fix, I realised that the code in `dsl/` is autogenerated.

2. I decided a safer option was to use the `update_at_xpath(params)` route.  I added code to that helper to deal with `Builder` objects and tweaked `user_parameters()` in `dsl.rb` to use this route.

3. I tweaked `update(params)` in `dsl.rb` so that instead of appending a child `<<` it replaced the children.

Option 1 adds to the DSL files which are tweaked by hand, which doesn't seem ideal (see also #87).  Option 2 shouldn't affect existing code, but seems messier than option 3.  Option 3 is tidier than 2, but has the potential to affect existing code and test plans, so I'm wary of it despite all tests passing because I'm don't feel familiar enough with the rest of the code and the ins-and-outs of the jmeter XML (`idl.xml`).

Any of the 3 routes fixes the problem.  Any thoughts on which is preferred?  Once decided, I can submit a PR for any of them.

**Comment by alexives** [comment]
I'm having this same issue, and I'd love to see this fixed. Given the response in #87, it seems like option 2 is already an acceptable path.

**Comment by alexives** [comment]
@90kts Thanks for getting that fixed!
