### ISSUE TITLE
Flood results at: #{JSON.parse(response)["permalink"]}

### ISSUE THREAD

**Issue by alexives** [flood-io/ruby-jmeter#91]
Calling .flood seems returns: `Flood results at: #{JSON.parse(response)["permalink"]}` rather than the actual message... I was able to find the results through the dashboard, but it seems odd that it doesn't work.

**Comment by 90kts** [comment]
Hi please update to latest gem, there was an issue here https://github.com/flood-io/ruby-jmeter/commit/cf8103a9ac7877e26ab7b5b695a8ba866b17577d

**Comment by alexives** [comment]
Yep! Works now, thanks!
