### ISSUE TITLE
URLs Generated by ruby-jmeter's flood integration don't work

### ISSUE THREAD

**Issue by alexives** [flood-io/ruby-jmeter#93]
The URL's that are generated by the ruby-jmeter flood integration don't seem to point at anything. They all say "Flood not found" when used. I can still see running floods if I go in through the UI so it's not the end of the world, just an annoyance.

**Comment by ivanvanderbyl** [comment]
Hi @alexives thanks for reporting this. Basically we need to set the `privacy_flag` to `public` for this to work correctly. I'll look at getting that fixed up.

**Comment by ivanvanderbyl** [comment]
As per the readme, if you set the `privacy_flag` in the DSL it should generate a URL you can open without being signed in to Flood:

```ruby
test do
  threads count: 10 do
    visit name: 'Google Search', url: 'http://google.com'
  end
end.flood(
  ENV['FLOOD_API_TOKEN'],
  name: 'Demo',
  privacy_flag: 'public',
)
```
