### ISSUE TITLE
Override JMeter properties

### ISSUE THREAD

**Issue by marimiyachi** [flood-io/ruby-jmeter#98]
At one point, there was support for overriding the default JMeter properties with something like `run(properties: [path to properties file])`. It looks like support for that configuration is [no longer available](https://github.com/flood-io/ruby-jmeter/blob/master/lib/ruby-jmeter/dsl.rb#L41). Was there a reason for removing it? Could there be something added to that line like `#{"-p params[:properties]" if params[:properties] }`?

**Comment by 90kts** [comment]
It was omitted because we weren't setting custom properties from this gem for use on Flood IO, however happy to add it back in for non-flood users of this gem.

**Comment by marimiyachi** [comment]
Great - I've just submitted a [PR](https://github.com/flood-io/ruby-jmeter/pull/99).

**Comment by 90kts** [comment]
Thanks, 3.0.8 has your changes
